development:
  facebook_app_id: 516249038840105
  facebook_app_secret: 853ef45531bebea89671903d5fa7386f
  github_app_id: d3261e3eeebf1cc34a25
  github_app_secret: bfc426b800177075dae6f582515a71a930b3eed0

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  github_app_id: <%= ENV["GIHUB_APP_ID"] %>1
  github_app_secret: <%= ENV["GIHUB_APP_SECRET"] %>
